### ISSUE TITLE
ngOptions from ngResource dont populatre until 1 refresh (why?)

### ISSUE THREAD

**Issue by mobiusinversion** [localytics/angular-chosen#106]
Hi there,
I am using chosen to populate a select box, 

    <select chosen="" 
                data-ng-model="coolThing" 
                data-ng-options="thing for thing in coolThings" 
                class="chosen-select input-md"></select>

And in my Controller:

      CoolThingsFactory.query(function(results) {
         $scope.coolThings = results;
       });

When I start my server and load the page, nothing is shown in the dropdown, though when I refresh the page, and every page refresh after that, the select populates correctly.  Am I doing something wrong above?  Btw, this example does not work for me at all:

      $scope.beers = $resource('api/beers').query()

Since it, as I have been explained, happens asynchronously, that therefore one must set in the scope in the query callback.  Did that work in some previous version of angular?

**Comment by dkavanagh** [comment]
I'm seeing the same. I have a select that it built within an ng-repeat and uses ng-options. At times, it doesn't show the options, but other times it does. I notice when options aren't visible, the select that angular built has them. Looks like a race condition where directive or the options go first because what I'm seeing is intermittent. I'm going to try a chosen:update in a $timeout function after setting my datasource (in the scope).

**Comment by dkavanagh** [comment]
Following up.. I create my selects w/ chosen in an ng-repeat on a hidden tab. When doing that, the chosen doesn't show the options. If I click the tab (to show it) before it loads the data that drives the select options, it renders just fine. So, I used an ng-if="tabindex==2" in the wrapper div for the 2nd tab and that solved the problem! It just won't try rendering the selects prior to me showing that tab.

**Comment by fadelardi** [comment]
Try: ng-if="beers.$resolved on your select.

**Comment by rayit** [comment]
How should I implement this?


This is in the html and code.

The third part is if I click on edit and want to fill in the brand in the chosen select.

It does not seem to work...

$http({
   method: "GET",
   url: urlBrands
}).success( function(res) {
    $scope.brands = res.result;
    $scope.article.brand = $scope.brands[0];
});

 Merk:
<select
  chosen
  class="form-control"
  novalidate=""
  data-placeholder="Merk"
  ng-model="article.brand"
  ng-options="b.name for b in brands"
  ng-change="changeBrand()"
  ng-if="article.brand.$resolved"
  >
<option></option>
</select

$scope.edit = function(article) {

    console.log(article);

    // set dropdowns
    // @TODO does not work
    $scope.article.brand = article.brand;

...

Is there a solution for this.

Many thanks!

----------------------------------------------------------------------
Raymond Marx
rmarx@rayit.com


________________________________
Van: fadelardi <notifications@github.com>
Verzonden: vrijdag 4 september 2015 17:08
Aan: localytics/angular-chosen
Onderwerp: {Disarmed} Re: [angular-chosen] ngOptions from ngResource dont populatre until 1 refresh (why?) (#106)


Try: ng-if="beers.$resolved on your select.

-
Reply to this email directly or view it on GitHub<https://github.com/localytics/angular-chosen/issues/106#issuecomment-137761722>.

--
This message has been scanned for viruses and
dangerous content by MailScanner<http://www.mailscanner.info/>, and is
believed to be clean.

**Comment by simison** [comment]
@rayit Something like
```javascript
$scope.brands = $http({
  method: "GET",
  url: urlBrands
}).success( function(res) {
  $scope.article.brand = $scope.brands[0];
  return res.result;
});
```
```
<select
  chosen
  ng-options="b.name for b in brands"
  ng-if="article.brands.$resolved">
```

PS. I recommend Using a separate [data service](https://github.com/johnpapa/angular-styleguide#data-services) instead of calling `$http` directly from the controller. Even better would be to [resolve them at the route](https://github.com/johnpapa/angular-styleguide#route-resolve-promises) so that your controller has only logic related to the view, not data.

PSS. Could you put your code into code-blocks please; https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by rayit** [comment]
Many thanks, this gives me a solution for the problem!

ng-if="article.brands.$resolved" is not needed for me.


greetings
Raymond
RayIT
