### ISSUE TITLE
Angular 1.4.9 compatibility

### ISSUE THREAD

**Issue by gserg** [localytics/angular-chosen#155]
Changes in Angular v1.4.9 (re-define ngModelCtrl.$render in the select postLink fn)
https://github.com/angular/angular.js/commit/529b2507bdb4fcc22dfa0f7ab462c79fc78d1413
are not compatible with current angular-chosen version
https://github.com/localytics/angular-chosen/blob/master/src/chosen.coffee#L74

**Comment by simison** [comment]
Oh, that's a bummer. This package hasn't been updated for a while and there are quite a few open pull requests.

Wonder if anyone at Localytics has any incentive to keep this up to date?

**Comment by aliakhtar** [comment]
Ditto. Just tried this, nothing seems to happen

**Comment by gserg** [comment]
I'm trying to find some solution...

Demo apps to reproduce a bug:
v1.4.8 http://embed.plnkr.co/RuXmm5WWNhAkXI7Y5Xf0/
v1.4.9 http://embed.plnkr.co/Qv62lC1rTZ5jnEKUVHWU/

**Comment by rubenspgcavalcante** [comment]
:+1:

**Comment by akotlar** [comment]
In case you're still having trouble with this. Change lines 69-72 from:
`js
if (ngModel) {
            origRender = ngModel.$render;
            ngModel.$render = function() {
              origRender();
              return initOrUpdate();
            };
`
to
`js
if (ngModel) {
 initOrUpdate();
`

This is related to the following 1.4.9 change: https://github.com/angular/angular.js/commit/529b2507bdb4fcc22dfa0f7ab462c79fc78d1413

Since ngModel.$render is redefined in the postLink, angular-chosen's further redefinition gets overwritten.

**Comment by douglasward** [comment]
Great, thanks for this!

**Comment by akotlar** [comment]
I've updated the solution; this now works to update selected value on ngModel updates, in absence of track by #157.

**Comment by simison** [comment]
@jr314159 any changes getting this in soon?

**Comment by lpsBetty** [comment]
+1

**Comment by stenmuchow** [comment]
+1

**Comment by leocaseiro** [comment]
+1

**Comment by leocaseiro** [comment]
@pkarl, Could you please merge  #157?

**Comment by leocaseiro** [comment]
Maybe @beezee, @jasonrdsouza, @trisweb  who are more active on github?

**Comment by lpsBetty** [comment]
@leocaseiro I am really glad that you made that PR, but do you know why it isn't merged yet?

**Comment by leocaseiro** [comment]
Hi @lpsBetty, actually wasn't me. It was @akotlar with the PR #157.

The reason the localytics team didn't accept the PR is that the projects seems to be abandoned. I haven't seen any action since the Jan 2015 which is a shame for a nice project like this one. I'm thinking in fork and look after this project on my own.
